build:
  maxIssues: 0

formatting:
  active: true

complexity:
  LongMethod:
    active: true
    threshold: 220
  TooManyFunctions:
    active: true
    thresholdInClasses: 20
    thresholdInFiles: 30
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

style:
  MagicNumber:
    active: false
